services:
  - type: web
    name: gym-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production

  - type: cron
    name: daily-scraper
    schedule: "40 20 * * *"  # Every day at 8:40 PM UTC (3:40 PM Texas Time)    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python daily_scraper.py"
